### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by evdama** [ukchukx/svelte-inline-input#3]
First and foremost let me say thanks, double thanks in fact, this package is brilliant! 👍

I'd link the [medium article](https://medium.com/@ukchukx/creating-an-inline-input-component-in-svelte-and-publishing-to-npm-84274be1aa73) from the github Readme and maybe put the animated gif from the medium article page there as well so folks get a quick grasp of how cool this package actually is 😃 

One thing I was thinking about is how to do some input validation with svelte-inline-input?!

I'm currently using https://github.com/tjinauyeung/svelte-forms-lib with it's custom helpers such as `<Form>` and yup https://svelte-forms-lib-sapper-docs.now.sh/helpers but I figure I'd ask you how you do it and then maybe https://svelte-forms-lib-sapper-docs.now.sh/yup is something that could work together with svelte-inline-input?

Would be brilliant if `<InlineInput>` would be another `<Field>` like here https://svelte-forms-lib-sapper-docs.now.sh/field

Then using it would look something like this
```js
  <script>
    import { Form, Field } from "svelte-forms-lib";
    import * as yup from "yup";

    const formProps = {
      initialValues: {
        text: "",
        email: "",
        password: "",
        number: 0,
        date: "",
        hobby:""
      },
      validationSchema: yup.object().shape({
        text: yup.string(),
        email: yup.string().email(),
        password: yup.string(),
        number: yup.number(),
        date: yup.date(),
        hobby: yup.string()
      }),
      onSubmit: values => {
        alert(JSON.stringify(values, null, 2));
      }
    };
  </script>

  <Form {...formProps}>
    <label>input[type=text]</label>
    <Field name="text" type="text" />

    <label>input[type=password]</label>
    <Field name="password" type="password" />

    <label>input[type=email]</label>
    <Field name="email" type="email" />

    <label>input[type=number]</label>
    <Field name="number" type="number" />

    <label>input[type=date]</label>
    <Field name="date" type="date" />

    <label>input[type=inline]</label>            // <--- using svelte-inline-input 🤔
    <Field name="hobby" type="inline" />

    <button type="submit">submit</button>
  </Form>
```

**Comment by ukchukx** [comment]
Thanks for the kind words, @evdama.
I've updated the README in line with your suggestions.
As for validation, you could plug it in a blur handler e.g. `<InlineInput on:blur={validationHandler} />`. 
Don't know if `svelte-forms-lib` provides such support, but one way would be to customize the input component of a `Field` using slots.
